import { useState } from 'react';
import type { Config, McpAction, McpProviderId, McpProviderStatus, McpStatus } from '../../types/config';
import { PageHeader } from '../../components/PageHeader';

export function McpConnection({ config, status, onToggle, onAction }: { config: Config; status: McpStatus; onToggle: (enabled: boolean) => Promise<void>; onAction: (action: McpAction, provider?: McpProviderId) => Promise<unknown> }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [preview, setPreview] = useState<{ title: string; text: string }>();
  const run = async (action: McpAction, provider?: McpProviderId) => { setBusy(true); setError(''); try { const result = await onAction(action, provider) as { preview?: string; note?: string; connection?: { message?: string } } | undefined; if (action === 'preview' && result) setPreview({ title: 'Provider 연결 설정 미리보기', text: `${result.note ?? ''}\n\n${result.preview ?? ''}`.trim() }); if (action === 'check' && result?.connection?.message) setPreview({ title: '실제 연결 확인 안내', text: result.connection.message }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'MCP 작업을 처리하지 못했습니다.'); } finally { setBusy(false); } };
  const removeWithPreview = async () => { setBusy(true); setError(''); try { const result = await onAction('preview') as { preview?: string; note?: string }; const text = `${result.note ?? ''}\n\n${result.preview ?? ''}`.trim(); setPreview({ title: '제거 전 연결 설정 확인', text }); if (window.confirm(`다음 JuTell 관리 블록만 제거할까요?\n\n${text}`)) await onAction('remove'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'MCP 설정 제거를 처리하지 못했습니다.'); } finally { setBusy(false); } };
  const runWithConfirm = async (action: 'connect' | 'disconnect' | 'set-default', provider: McpProviderStatus) => {
    const message = action === 'connect' ? `${provider.label} 연결을 시작할까요? 기존 설정은 보존하고 JuTell MCP 항목만 추가합니다.` : action === 'disconnect' ? `${provider.label} 연결을 끊을까요? JuTell MCP는 비활성화되고 설정 항목은 유지됩니다.` : `${provider.label}만 활성화하고 다른 Agent의 JuTell 연결을 끌까요?`;
    if (window.confirm(message)) await run(action, provider.id);
  };
  const statusLabel = { running: '실행 중', stopped: '중지됨', starting: '시작 중', error: '오류' }[status.server.state];
  const preparationLabel = { not_registered: '설정 미등록', registered: '등록됨', enabled: '활성화됨', error: '오류' }[status.preparation];
  const actualLabel = { not_checked: '확인하지 않음', success: '마지막 확인 성공', failure: '마지막 확인 실패' }[status.connection.state];
  const activeProviders = status.providers.filter((provider) => provider.enabled && provider.status !== 'planned').map((provider) => provider.label).join(', ') || '없음';
  return <section>
    <PageHeader eyebrow="Agent 연결" title="AI Agent 연결 준비 상태" description="MCP는 선택 기능입니다. Skill 방식은 MCP가 꺼져도 계속 사용할 수 있습니다." />
    <div className="safe-info"><strong>먼저 알아둘 점</strong><span>서버 실행, Provider 설정 등록, 실제 도구 호출은 서로 다른 상태입니다. 서버가 실행 중이어도 연결 완료로 표시하지 않습니다.</span></div>
    {error && <p className="field-error" role="alert">{error}</p>}
    <div className="panel mcp-panel"><div className="section-heading"><div><p className="eyebrow">현재 사용 방식</p><h3>Skill 방식은 항상 유지됩니다.</h3></div><span className="status-pill success">기본 연결</span></div><p>AGENTS.md, Skill, `.jutell.json`을 AI Agent가 읽는 방식입니다. MCP를 중지하거나 설정을 제거해도 이 방식은 바뀌지 않습니다.</p></div>
    <div className="panel mcp-panel"><div className="section-heading"><div><p className="eyebrow">Provider 지원 범위</p><h3>연결하기 버튼 하나로 연결을 준비합니다.</h3></div><span className="status-pill success">Codex 지원 · OpenCode 베타</span></div><p>연결하기는 기존 Provider 설정을 보존하고 JuTell MCP 항목만 추가합니다. 연결 끊기는 선택한 Provider만 비활성화합니다.</p><div className="provider-grid">{status.providers.map((provider) => <div className="provider-card" key={provider.id}><div className="provider-card-head"><strong>{provider.label}</strong><span>{provider.status === 'supported' ? '현재 지원' : provider.status === 'beta' ? '베타' : '준비 중'}</span></div><small>설치: {provider.detected ? '감지됨' : '미감지'} · MCP: {provider.registered ? provider.enabled ? '활성' : '비활성' : '미등록'}{provider.conflict ? ' · 충돌' : ''}{provider.lastCheckedAt ? ` · 점검 ${new Date(provider.lastCheckedAt).toLocaleString('ko-KR')}` : ''}</small>{provider.status === 'planned' ? <p className="muted">연결 준비 중입니다.</p> : <div className="button-row provider-actions">{provider.conflict ? <span className="muted">관리되지 않는 항목이 있어 자동 변경하지 않습니다.</span> : <><button className="primary" disabled={busy || provider.enabled} onClick={() => void runWithConfirm('connect', provider)}>연결하기</button><button className="secondary" disabled={busy || !provider.registered || !provider.enabled} onClick={() => void runWithConfirm('disconnect', provider)}>연결 끊기</button><button className="secondary" disabled={busy || provider.enabled} onClick={() => void runWithConfirm('set-default', provider)}>기본 Agent로 사용</button></>}</div>}</div>)}</div></div>
    <div className="panel mcp-panel"><div className="section-heading"><div><p className="eyebrow">MCP 방식</p><h3>로컬 읽기 전용 연결</h3></div><span className={`status-pill ${config.mcp.enabled ? 'success' : 'warning'}`}>{config.mcp.enabled ? '사용 켜짐' : '사용 꺼짐'}</span></div><label className="mcp-toggle"><input type="checkbox" checked={config.mcp.enabled} onChange={(event) => void onToggle(event.target.checked)} disabled={busy} /><span title="MCP는 AI Agent가 로컬 설정을 읽는 선택형 연결 방식입니다. 안 쓰면 Skill 방식만 사용합니다.">JuTell MCP 사용</span></label><p className="muted">MCP를 켜도 자동으로 AI Agent 세션에 연결됐다고 표시하지 않습니다. 운영체제 시작 시 자동 실행은 항상 OFF입니다.</p>{status.preparation === 'enabled' && <div className="safe-info"><strong>✓ AI Agent 연결 준비 완료</strong><span>새 세션부터 사용할 수 있습니다. 실제 도구 호출 여부는 해당 Provider에서 확인할 수 있습니다.</span></div>}<div className="mcp-status-grid"><div><span>서버 실행 상태</span><strong>{statusLabel}</strong>{status.server.error && <small>{status.server.error}</small>}</div><div><span>AI Agent 연결 준비</span><strong>{preparationLabel}</strong><small>활성 Provider: {activeProviders}</small></div><div><span>실제 도구 호출</span><strong>{actualLabel}</strong><small>{status.connection.lastCheckedAt ? `마지막 점검: ${new Date(status.connection.lastCheckedAt).toLocaleString('ko-KR')}` : '해당 Agent 세션에서 직접 확인할 수 있습니다.'}</small></div><div><span>Skill 대체 경로</span><strong>사용 가능</strong><small>{status.skillFallback.message}</small></div></div></div>
    <div className="panel mcp-panel"><h3>작업</h3><p className="muted">설정 생성과 제거 전에는 변경 내용을 미리 확인합니다. 기존 Provider 설정은 보존하고 JuTell 관리 블록만 다룹니다.</p><div className="button-row mcp-actions"><button className="secondary" disabled={busy} onClick={() => void run('start')}>MCP 서버 시작</button><button className="secondary" disabled={busy} onClick={() => void run('stop')}>MCP 서버 중지</button><button className="secondary" disabled={busy} onClick={() => void run('preview')}>연결 설정 미리 보기</button><button className="primary" disabled={busy || !config.mcp.enabled} onClick={() => void run('register')}>Provider 연결 설정 생성</button><button className="secondary" disabled={busy} onClick={() => void run('check')}>연결 점검</button><button className="danger" disabled={busy || !status.codex.registered} onClick={() => void removeWithPreview()}>설정 제거</button></div><div className="callout"><strong>설정 제거 전 확인</strong><span>현재 Provider 설정의 JuTell 관리 블록만 제거합니다. Skill 방식은 그대로 유지됩니다.</span></div></div>
    {preview && <div className="panel mcp-preview"><h3>{preview.title}</h3><pre>{preview.text}</pre></div>}
    <div className="panel mcp-panel"><h3>AI Agent에서 실제 연결 확인하기</h3><p>아래 문구를 새 작업에 전달하면 현재 사용 가능한 Provider 도구 목록과 호출 결과를 직접 확인할 수 있습니다.</p><pre>JuTell MCP 연결 상태를 확인해주세요.
사용 가능한 AI Agent 도구 목록에서 JuTell 도구를 찾고,
get_bridge_status와 get_active_features를 호출해주세요.
실제 호출 결과를 기준으로 연결 성공 또는 실패를 보고해주세요.</pre></div>
  </section>;
}
