import { useMemo, useState } from 'react';
import type { Config, Feedback, FeedbackInput, Profile } from '../../types/config';
import { FEATURE_CATALOG } from '../../lib/catalog';
import { PageHeader } from '../../components/PageHeader';

const today = () => new Date().toISOString().slice(0, 10);
const emptyFeedback = (config: Config): FeedbackInput => ({
  date: today(), projectAlias: '', taskType: 'feature', profile: config.profile, activeFeatures: FEATURE_CATALOG.filter((item) => config.features[item.id]).map((item) => item.id),
  perceivedLength: 'appropriate', understandable: 'yes', mostUsefulFeature: '', unnecessaryFeature: '', missingInfo: '', inaccurateContent: '', reuseConfig: 'unknown', improvementIdea: '', severity: 'low', status: 'noted',
});

const taskLabels: Record<string, string> = { screen: '화면', feature: '기능', docs: '문서', settings: '설정', other: '기타' };
const featureLabel = (id: string) => FEATURE_CATALOG.find((item) => item.id === id)?.label ?? id;

export function BetaJournal({ config, feedback, onSave, onDelete }: { config: Config; feedback: Feedback[]; onSave: (input: FeedbackInput, id?: string) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [form, setForm] = useState<FeedbackInput>(() => emptyFeedback(config));
  const [editingId, setEditingId] = useState<string>();
  const [filterSeverity, setFilterSeverity] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');
  const [filterProfile, setFilterProfile] = useState('all');
  const [filterTask, setFilterTask] = useState('all');
  const [error, setError] = useState('');
  const filtered = useMemo(() => feedback.filter((item) => (filterSeverity === 'all' || item.severity === filterSeverity) && (filterStatus === 'all' || item.status === filterStatus) && (filterProfile === 'all' || item.profile === filterProfile) && (filterTask === 'all' || item.taskType === filterTask)), [feedback, filterSeverity, filterStatus, filterProfile, filterTask]);
  const update = <K extends keyof FeedbackInput>(key: K, value: FeedbackInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await onSave(form, editingId); setForm(emptyFeedback(config)); setEditingId(undefined); } catch (caught) { setError(caught instanceof Error ? caught.message : '피드백을 저장하지 못했습니다.'); } };
  const edit = (item: Feedback) => { const { id, createdAt, updatedAt, ...input } = item; void createdAt; void updatedAt; setEditingId(id); setForm(input); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <section>
    <PageHeader eyebrow="Beta Journal" title="개인 베타 기록" description="실제 사용 중 느낀 점을 직접 기록합니다. 민감한 내용이나 프로젝트 식별 정보는 적지 마세요." />
    <form className="panel feedback-form" onSubmit={submit}><div className="form-title"><h3>{editingId ? '피드백 수정' : '새 피드백 기록'}</h3>{editingId && <button type="button" className="text-button" onClick={() => { setEditingId(undefined); setForm(emptyFeedback(config)); }}>새 기록으로 돌아가기</button>}</div>
      {error && <p className="field-error" role="alert">{error}</p>}
      <div className="form-grid"><label>날짜<input required type="date" value={form.date} onChange={(e) => update('date', e.target.value)} /></label><label>익명 프로젝트 별칭<input required value={form.projectAlias} maxLength={100} placeholder="예: 작은 웹앱 A" onChange={(e) => update('projectAlias', e.target.value)} /></label><label>작업 종류<select value={form.taskType} onChange={(e) => update('taskType', e.target.value)}>{Object.entries(taskLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>Profile<select value={form.profile} onChange={(e) => update('profile', e.target.value as Profile)}>{(['minimal', 'balanced', 'learning', 'detailed'] as Profile[]).map((key) => <option key={key}>{key}</option>)}</select></label></div>
      <fieldset><legend>활성 Feature</legend><div className="checkbox-grid">{FEATURE_CATALOG.map((feature) => <label key={feature.id}><input type="checkbox" checked={form.activeFeatures.includes(feature.id)} onChange={(e) => update('activeFeatures', e.target.checked ? [...form.activeFeatures, feature.id] : form.activeFeatures.filter((id) => id !== feature.id))} />{feature.label}</label>)}</div></fieldset>
      <div className="form-grid"><label>보고서 길이 체감<select value={form.perceivedLength} onChange={(e) => update('perceivedLength', e.target.value as FeedbackInput['perceivedLength'])}><option value="short">짧음</option><option value="appropriate">적당함</option><option value="long">김</option></select></label><label>이해하기 쉬웠나요?<select value={form.understandable} onChange={(e) => update('understandable', e.target.value as FeedbackInput['understandable'])}><option value="yes">예</option><option value="partial">부분적으로</option><option value="no">아니오</option></select></label><label>같은 설정 재사용<select value={form.reuseConfig} onChange={(e) => update('reuseConfig', e.target.value as FeedbackInput['reuseConfig'])}><option value="yes">예</option><option value="no">아니오</option><option value="unknown">모르겠음</option></select></label><label>심각도<select value={form.severity} onChange={(e) => update('severity', e.target.value as FeedbackInput['severity'])}><option value="low">낮음</option><option value="medium">중간</option><option value="high">높음</option></select></label><label>조치 상태<select value={form.status} onChange={(e) => update('status', e.target.value as FeedbackInput['status'])}><option value="noted">기록만 함</option><option value="needs_reproduction">재현 필요</option><option value="planned">수정 예정</option><option value="confirmed">확인 완료</option></select></label></div>
      <div className="form-grid textareas"><label>가장 유용했던 Feature<textarea value={form.mostUsefulFeature} maxLength={2000} onChange={(e) => update('mostUsefulFeature', e.target.value)} /></label><label>불필요했던 Feature<textarea value={form.unnecessaryFeature} maxLength={2000} onChange={(e) => update('unnecessaryFeature', e.target.value)} /></label><label>빠진 정보<textarea value={form.missingInfo} maxLength={2000} onChange={(e) => update('missingInfo', e.target.value)} /></label><label>사실과 달랐던 내용<textarea value={form.inaccurateContent} maxLength={2000} onChange={(e) => update('inaccurateContent', e.target.value)} /></label><label>개선 아이디어<textarea value={form.improvementIdea} maxLength={2000} onChange={(e) => update('improvementIdea', e.target.value)} /></label></div>
      <div className="form-footer"><small>Prompt, 코드, 경로, 오류 원문, 비밀정보는 기록하지 않습니다.</small><button className="primary" type="submit">{editingId ? '피드백 수정' : '피드백 저장'}</button></div>
    </form>
    <div className="panel"><div className="form-title"><h3>기록 목록 ({filtered.length})</h3><div className="filters"><select aria-label="심각도 필터" value={filterSeverity} onChange={(e) => setFilterSeverity(e.target.value)}><option value="all">모든 심각도</option><option value="low">낮음</option><option value="medium">중간</option><option value="high">높음</option></select><select aria-label="상태 필터" value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}><option value="all">모든 상태</option><option value="noted">기록만 함</option><option value="needs_reproduction">재현 필요</option><option value="planned">수정 예정</option><option value="confirmed">확인 완료</option></select><select aria-label="Profile 필터" value={filterProfile} onChange={(e) => setFilterProfile(e.target.value)}><option value="all">모든 Profile</option>{(['minimal', 'balanced', 'learning', 'detailed'] as Profile[]).map((key) => <option key={key}>{key}</option>)}</select><select aria-label="작업 종류 필터" value={filterTask} onChange={(e) => setFilterTask(e.target.value)}><option value="all">모든 작업</option>{Object.entries(taskLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></div>{filtered.length === 0 ? <p className="empty">아직 기록이 없습니다.</p> : <div className="feedback-list">{filtered.map((item) => <article className="feedback-item" key={item.id}><div><strong>{item.projectAlias}</strong><span>{item.date} · {taskLabels[item.taskType]} · {item.profile}</span></div><p>{item.inaccurateContent || item.improvementIdea || item.missingInfo || '추가 메모 없음'}</p><small>활성 Feature: {item.activeFeatures.map(featureLabel).join(', ') || '없음'}</small><div className="item-actions"><button className="text-button" onClick={() => edit(item)}>편집</button><button className="text-button danger-text" onClick={() => { if (window.confirm('이 피드백을 삭제할까요?')) void onDelete(item.id); }}>삭제</button></div></article>)}</div>}</div>
  </section>;
}
